env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - react-app
  - react-app/jest
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - unused-imports
  - import
rules:
  import/no-relative-parent-imports: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
        - object
        - type
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
      newlines-between: always
  '@typescript-eslint/consistent-type-imports':
    - error
    - prefer: type-imports
  unused-imports/no-unused-imports: 2
  '@typescript-eslint/no-unused-vars': 1
  '@typescript-eslint/no-explicit-any': 2
  no-else-return: 2
  react/jsx-uses-react: 0
  react/react-in-jsx-scope: 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/explicit-module-boundary-types': 1
  '@typescript-eslint/no-empty-function': 0
  no-restricted-imports:
    - error
    - patterns:
        - group: ['components/*']
          message: Please import components from 'components' index file instead.
